// Generated by CoffeeScript 1.7.1
(function() {
  var targets;

  targets = (function() {
    function targets(refs) {
      this.refs = refs;
    }

    targets.highlight = function(tar) {
      return this.refs.highlight(tar);
    };

    return targets;

  })();

}).call(this);
